### PR TITLE
add address property to Document model

### PR DESCRIPTION
**Pull request by missinglink**
the `address` property is already defined in `pelias/schema` [1] this PR simply exposes getter/setter methods to provide an interface to modify the address data.

[1] https://github.com/pelias/schema/blob/master/mappings/poi.js#L7

### CODE REVIEW

**Comment by hkrishna** [comment]
+1

**Comment by dianashk** [comment]
Are we not concerned with validating which children are added to the Address model? Would that just be done in a different place in the code or not at all? Otherwise code looks fine. 
+1

**Comment by missinglink** [comment]
I would love to see a `model.Address` added to this repo to handle further validation of address specific data. For now it's a free-form object which accepts any keys and truthy+stringy values.

@sevko there was some work done in the past regarding a `new Address()` model; which would be useful for the input string parsing functionality we have been discussing.

**Comment by missinglink** [comment]
```bash
$ npm publish
npm http PUT https://registry.npmjs.org/pelias-model
npm http 201 https://registry.npmjs.org/pelias-model
+ pelias-model@0.1.0
```

**Pull request merged**
