### PR TITLE
allow aliases for address fields

### PR DESCRIPTION
**Pull request by missinglink**
this PR enables each `address_parts.*` field to have multiple aliases.

developers can use the new methods `setAddressAlias` and `getAddressAliases` to get/set values.

the reason this works is because elasticsearch fields can either be scalars or arrays of scalars, so no changes are required in elasticsearch for this to function.

I did some tests to ensure that the tokens from the aliases aren't mixed with the each other, elasticsearch has an option called `position-increment-gap` which ensures this doesn't happen.

This feature will allow multiple 'aliases' for each address, including `address_parts.zip` and all other fields.

### CODE REVIEW

**Comment by missinglink** [comment]
The PR is almost identical to the one which added aliases to name.

The only thing I changed which might cause issue is adding:

```javascript
validate.type('string', value);
validate.truthy(value);
```

This strongly enforces that the values must be strings, which they should be anyway because they are stored and retrieved as strings.

If an importer tried to import a field such as `zip` or `housenumber` as an integer it would throw an error, although I don't think this is how any of our current importers behaves?

**Comment by missinglink** [comment]
BUUUMP!

**Comment by orangejulius** [comment]
oh, yeah. this is very important. give me a bit to read the code again, and also before we merge this let me update semantic-release's settings and ensure the NPM token is up to date

**Comment by orangejulius** [comment]
looks good, what do we have planned to use this for again?

**Pull request merged**
